### ISSUE TITLE
will dojo support react component?

### ISSUE THREAD

**Issue by xiechj** [dojo/interop#45]
There are many React third party UI components now. If we can use these components，that would be great.

**Comment by agubler** [comment]
While we don't currently have any official plans to support React components, we're confident this could be done in user land some sort of wrapper/adapter at the moment.

I have moved this to the dojo/interop repository, to track any efforts in the future.

**Comment by agubler** [comment]
This is not something we are likely to do as part of the official framework packages, however it would be possible in user land if required.
